name: ssh

on:
  push: # 워크플로우 실행 조건 이벤트
    branches: # 워크플로우 실행 조건 브렌치
      - main

jobs:
  ssh-agent: # job 이름
    runs-on: ubuntu-24.04 # github 워크스페이스 환경

    steps: # 실행할 작업(step)
      - name: run ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 원격 서버를 신뢰할 수 있는 서버로 등록하는 과정
      # known_hosts : 원격 서버들의 지문이 저장된 파일
      - name: Add Remote Server Fingerprint to Known Hosts
        run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST}} >> ~/.ssh/known_hosts || true

      - name: create file on remote server
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST}} "touch 'hello world.txt'"
