name: ssh

on:
  push: # 워크플로우 실행 조건 이벤트
    branches: # 워크플로우 실행 조건 브렌치
      - main

jobs:
  ssh-agent: # job 이름
    runs-on: ubuntu-24.04 # github 워크스페이스 환경

    steps: # 실행할 작업(step)
      - name: run ssh-agent
        uses: webfactory/ssh-agent@0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}
